### ISSUE TITLE
Telegram support in v4

### ISSUE THREAD

**Issue by jfberry** [KartulUdus/PoracleJS#216]
Blocker for some v3 users who don't want to leave telegram behind

**Comment by memcoreDE** [comment]
We use Telegram in combination with PoracleJS v3 and I know many other user/server they use Telegram also. 
**Please don´t leave telegram behind.**

**Comment by jfberry** [comment]
It would certainly be helpful to have some users that care about this starting to contribute support; I don't use telegram on my server.  Looking at v3 it looks like the telegram code was a copy/paste which is inefficient / makes it difficult to maintain going forward.  A debate about whether this is the right approach for v4 or whether some re-factoring to take the core of the commands out into shared code and building a communication/abstraction layer would be worthwhile.

I can imagine that messenger support would be valued by some people (although unofficial bots get banned quite frequently and going through the official route may not be viable)

**Comment by pogoteambrindisi** [comment]
Thanks a lot for opening this issue. I believe many Telegram communities are still using PoracleJS and it is a pity that such version lags quite a lot behind. Specifically the following things were not implemented in Telegram v3 and make PoracleJS for Telegram appear outdated:

- Support for tracking of PvP mons and customized messages for PvP-related spawns
- Support for all forms
- Weather change alerts
- The admin of the group having the possibility to unregister one of the users (right now sending the command /unregister @[user] does not work and it actually results in the admin itself becoming unregistered)
- Gen VI support and stats

Not sure if I forgot anything... We really hope this issue is brought forward... Thanks again!

**Comment by jfberry** [comment]
PR246 now supports Telegram
(unregistering another user is not possible but the rest are!)

**Comment by jfberry** [comment]
PR now feature complete, will be merged soon

**Comment by jfberry** [comment]
Merged
