### ISSUE TITLE
feature idea: allow user to select the minimum despawn time for reports

### ISSUE THREAD

**Issue by philcerf** [KartulUdus/PoracleJS#347]
Hey.

Would be nice if the users could configure the minimum despawn time needed, for anything to be reported.

Ideally one could set this at least per encounter type... but maybe even per rule(? - not sure whether this makes sense).

One could make this in two flavours:
- a plain time threshold, e.g. 10 minutes, if less, no report
- a time threshold that some scales with the distance of the object to the set location, i.e. the nearer something is, the less time is enough for a report - the further something is, the more time is required.

The idea is that a despawn time of 2 mins might be enough for an encounter in 40m distance, but no for something in 5 km.

Perhaps it would also make sense to store these as (separate?) profiles, so that one can quickly switch the values for everything, depending on whether one is by foot, on the bike, car, etc.

**Comment by jfberry** [comment]
I have seen a poracle fork that adds ‘t’ to the monster track which is a time in seconds spawn must be alive to alert. Probably doesn’t make any sense for other alert types. 

this seems like the most practical addition

**Comment by philcerf** [comment]
Well I agree for raid/egg,... but it could make sense for rare invasion types...

**Comment by Petap0w** [comment]
Honestly this feature isn’t really useful as most user will anyways set it at something between 3 and 5 minutes. 
you can’t reasonably set a value to alert only above on alerts that are from a central location where you won’t be 100% of the time anyways, or for alerts in an area where you could be any place when the alert shows. You could be at 5 min or 20 when it alerts because you’re moving in your day 
If you give too many options to users you’ll end up with half of them setting trackings with parameters they don’t even understand - at the cost of making the db query checking another test for everyone
